analyzer:
  errors:
    cascade_invocations: ignore
    inference_failure_on_function_invocation: ignore
    use_build_context_synchronously: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
