name: personal_expense_tracker
description: Personal expense tracker app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  formz: ^0.7.0
  freezed: ^2.5.7
  get_it: ^7.7.0
  intl: ^0.19.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
